--
- name: nginx-role
  src: https://github.com/NamorNinayzuk/nginx-role
  scm: git
  version: 0.0.1
- name: lighthouse-role
  src: https://github.com/NamorNinayzuk/lighthouse-role
  scm: git
  version: 0.0.3
- name: vector-role
  src: https://github.com/NamorNinayzuk/vector-role
  scm: git
  version: 0.0.4
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
# - src: git@gitlab.com:naturalis/core/analytics/ansible-clickhouse.git
  name: clickhouse
  scm: git
  version: "1.11.0"
